version: '3.9'
services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "${N8N_PORT}:5678"
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=5678
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      # опционально передаем ключ в окружение (в ноде OpenAI всё равно добавьте креды в UI)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # чтобы удобно использовать в выражениях n8n
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_COLLECTION=${QDRANT_COLLECTION}
    depends_on:
      - neo4j
      - qdrant
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

  neo4j:
    image: neo4j:5.23
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_server_memory_heap_initial__size=512M
      - NEO4J_server_memory_heap_max__size=1G
      - NEO4J_server_memory_pagecache_size=512M
    ports:
      - "7474:7474"   # HTTP (Browser/API)
      - "7687:7687"   # Bolt
    volumes:
      - neo4j_data:/data
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped

volumes:
  n8n_data:
  neo4j_data:
  qdrant_storage:
