name: Deploy to Render

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "$RENDER_DEPLOY_HOOK" ]; then
            echo "RENDER_DEPLOY_HOOK_URL secret is not set" && exit 1
          fi
          curl -fsS -X POST "$RENDER_DEPLOY_HOOK"

